### ISSUE TITLE
Unable to install using README instructions

### ISSUE THREAD

**Issue by eduard-bagdasaryan** [Mark-Simulacrum/pretty-generator#1]
When running the command from README: _npm run-script build_
get an error:

> pretty-generator@0.0.1 build /tmp/pretty-generator
> npm run build-without-logging
> pretty-generator@0.0.1 build-without-logging /tmp/pretty-generator
> npm run build-plugin && babel --plugins ./lib/babel-plugin-strip-logging.js src --out-dir lib
> pretty-generator@0.0.1 build-plugin /tmp/pretty-generator
> babel src/babel-plugin-strip-logging.js > lib/babel-plugin-strip-logging.js
sh: 1: cannot create lib/babel-plugin-strip-logging.js: Directory nonexistent
...

This step is OK when _lib_ directory is created manually.

**Comment by Mark-Simulacrum** [comment]
Thank you for reporting this issue, should be fixed now.
